import './globals.css'
import { Inter,Oxygen,Oxygen_Mono } from 'next/font/google'


const inter = Inter({ subsets: ['latin'],display:'swap',variable:'--font-oxygen' })

const oxygen= Oxygen({
  subsets: ['latin'],
  weight:'400',
  display:'swap',
  variable:'--font-oxygen'
})
const oxygen_mono=Oxygen_Mono({subsets: ['latin'],weight:'400', display:'swap', variable:'--font-oxygen-mono'})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='box-border'>
      <head></head>
      <body className={`${inter.variable} ${oxygen.variable} ${oxygen_mono.variable}`}>{children}</body>
    </html>
  )
}
